version: '3'
services:
  postgres:
    image: "postgres:14"
    hostname: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "sirio.neto97@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "asdf000"
    ports:
      - "54321:80"
    depends_on:
      - postgres
